### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by knuxify** [knuxify/SerialBowl#1]
- [x] Make closed terminal state look better
- [x] Add terminal settings: scrollback, ~~escape character handling~~, disable meta prints from serialbowl itself
- [x] Make theme auto-refresh when Adwaita theme variant is changed
- [x] Set the sidebar background to be the same as the headerbar
- [x] Add menu button, about window
- [x] Add message boxes for "reconnecting" state in auto reconnect mode
- [x] Add toasts for connection errors
- [x] Add logging support
